
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ems
    username: root
    password: 10082001
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
