# exposure
management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true

# Enable actuator/info
#custom to show helpful project info
spring:
  security:
    user:
      name: 'admin'
      password: '123'
  datasource:
    url: 'jdbc:mysql://localhost:3306/spring_mvc_customers'
    username: 'root'
    password: '10082001'
  data:
    rest:
      default-page-size: 8
# spring data rest

